### ISSUE TITLE
Demonstrate the use of `ortools` in the docs

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/bloptools#28]
https://developers.google.com/optimization/routing/tsp

Used in the code already here: https://github.com/NSLS-II/bloptools/blob/8697840dcd3ece5a96f6cf2c50c5e966dcbacb15/bloptools/utils.py#L3
We need to document it and provide an example or two.

**Comment by thomaswmorris** [comment]
Fixed in #30
